apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: personal-blog
resources:
  - wordpress-deployment.yaml
  - wordpress-ingress.yaml
  - wordpress-service.yaml
  - wp-content-persistentvolumeclaim.yaml
  - wordpress-namespace.yaml
